
CREATE DATABASE "sanita"
CONNECT TO "SANITA"

CREATE TABLE REQUESITION (REQUESITION_NUMBER INT NOT NULL ,STAFF_NUMBER INT NOT NULL,WARD_NUMBER VARCHAR(6) NOT NULL,DATE_REQUESTED DATE NOT NULL)

CREATE TABLE REQUESITIONDETAIL (REQUESITION_NUMBER INT NOT NULL,ITEM_NUMBER INT NOT NULL,QUANTITY INT NOT NULL)

CREATE VIEW VW_REQUESITIONDETAIL AS SELECT REQUESITIONDETAIL.REQUESITION_NUMBER, REQUESITIONDETAIL.ITEM_NUMBER, SUPPLY.ITEM_NAME, SUPPLY DESCRIPTION, REQUESITIONDETAIL.QUANTITY FROM REQUESITIONDETAIL, SUPPLY WHERE SUPPLY.ITEM_NUMBER = REQUESITIONDETAIL.ITEM_NUMBER

CREATE TABLE SUPPLIER (SUPPLIER_NUMBER INT NOT NULL,SUPPLIER_NAME VARCHAR(20) NOT NULL,ADDRESS VARCHAR(20) NOT NULL,TELNUMBER INT NOT NULL,FAXNUMBER INT NULL)

CREATE TABLE SUPPLY (ITEM_NUMBER INT NOT NULL,SUPPLIER_NUMBER INT NOT NULL,ITEM_NAME VARCHAR(50) NOT NULL,DESCRIPTION VARCHAR(100) NULL,QUANTITY INT NOT NULL,REORDER_LEVEL INT NOT NULL,UNIT VARCHAR(20), COST_PER_UNIT DECIMAL(7,2) NOT NULL,ITEM_TYPE INT NOT NULL,DOSAGE VARCHAR(20) NULL,METHOD_OF_ADMINISTRATION VARCHAR(5) NULL)

CREATE TABLE MEDICATION (MEDICATION_ID INT NOT NULL,STAFF_NUMBER INT NOT NULL,INPATIENT_ID INT NOT NULL,DATE_FILED DATE NOT NULL,TIME_FILED VARCHAR(5) NOT NULL)

CREATE TABLE MEDICATIONDETAIL (MEDICATION_ID INT NOT NULL,ITEM_NUMBER INT NULL,METHOD_OF_ADMINISTRATION VARCHAR(5) NULL,DOSAGE VARCHAR(20) NULL)

CREATE TABLE STAFF (STAFF_NUMBER INT NOT NULL,FIRSTNAME VARCHAR(50) NOT NULL,LASTNAME VARCHAR(50) NOT NULL,ADDRESS VARCHAR(100) NOT NULL,TELNUMBER INT NOT NULL,BIRTHDATE DATE NOT NULL,SEX VARCHAR(6) NOT NULL,NIN INT NOT NULL)

-- CREATE VIEW FOR VW_STAFF 

CREATE TABLE ACCOUNT (ACCOUNT_NO INT NOT NULL, STAFF_NUMBER INT, USERNAME VARCHAR(50), PASSCODE VARCHAR(50), ACCOUNT_TYPE INT)

CREATE VIEW VW_ACCOUNT AS SELECT ACCOUNT.ACCOUNT_NO, ACCOUNT.STAFF_NUMBER, STAFF.FIRSTNAME, STAFF.LASTNAME, ACCOUNT.USERNAME, ACCOUNT.PASSCODE, ACCOUNT.ACCOUNT_TYPE FROM ACCOUNT, STAFF WHERE ACCOUNT.STAFF_NUMBER = STAFF.STAFF_NUMBER

CREATE TABLE WORKEXPERIENCE (WORKEXPERIENCE_ID INT NOT NULL,STAFF_NUMBER INT NOT NULL,POSITION VARCHAR(5) NOT NULL,ORGANIZATION VARCHAR(20) NOT NULL,START_DATE DATE NOT NULL,END_DATE DATE NOT NULL)

CREATE TABLE QUALIFICATION (QUALIFICATION_ID INT NOT NULL,STAFF_NUMBER INT NOT NULL,DESCRIPTION VARCHAR(50) NOT NULL)

CREATE TABLE POSITIONHELD (POSITIONHELD_ID INT NOT NULL,STAFF_NUMBER INT NOT NULL,POSITION_ID INT NOT NULL,WORKSHIFTTYPE_ID INT NOT NULL,SALARY_ID INT NOT NULL,DATE_ASSIGNED DATE NOT NULL)

CREATE TABLE SALARY (SALARY_ID INT NOT NULL,SALARY FLOAT NOT NULL,DESCRIPTION VARCHAR(20) NOT NULL)

CREATE TABLE WORKSHIFTTYPE (WORKSHIFTTYPE_ID INT NOT NULL,SHIFT VARCHAR(10) NOT NULL,DESCRIPTION VARCHAR(20) NOT NULL)

CREATE TABLE ASSIGNEDWARD (WARD_NUMBER INT NOT NULL,STAFF_NUMBER INT NOT NULL,DATE_ASSIGNED DATE NOT NULL)

CREATE TABLE WARD (WARD_NUMBER VARCHAR(6) NOT NULL,NAME VARCHAR(15) NOT NULL,DESCRIPTION VARCHAR(50) NOT NULL)

CREATE TABLE BED (BED_ID INT NOT NULL,WARD_NUMBER VARCHAR(6) NOT NULL,DESCRIPTION VARCHAR(50) NOT NULL)

CREATE TABLE PATIENT (PATIENT_NUMBER INT NOT NULL,FIRSTNAME INT NOT NULL,LASTNAME VARCHAR(50) NOT NULL,ADDRESS VARCHAR(100) NULL,TELNUMBER INT NOT NULL,BIRTHDATE INT NOT NULL,SEX DECIMAL(7,2) NOT NULL,MARITAL_STATUS INT NOT NULL)

CREATE TABLE NEXTOFKIN (NEXTOFKIN_ID INT NOT NULL,PATIENT_NUMBER INT NOT NULL,FIRSTNAME VARCHAR(50) NOT NULL,LASTNAME VARCHAR(50) NOT NULL,ADDRESS VARCHAR(100) NOT NULL,TELNUMBER INT NOT NULL,RELATIONSHIP VARCHAR(15) NOT NULL)

CREATE TABLE INPATIENTRECORD (WORKEXPERIENCE_ID INT NOT NULL,STAFF_NUMBER INT NOT NULL,POSITION VARCHAR(5) NOT NULL,INPATIENT_ID INT NOT NULL,PATIENT_NUMBER INT NOT NULL,BED_ID INT NOT NULL,DATE_ARRIVED DATE NOT NULL,EXPECTED_DURATION INT NOT NULL,DATE_LEFT DATE NOT NULL)

CREATE TABLE OUTPATIENTRECORD (OUTPATIENT_ID INT NOT NULL,PATIENT_NUMBER INT NOT NULL,APPOINTMENT_NUMBER INT NOT NULL)

CREATE TABLE APPOINTMENT (APPOINTMENT_NUMBER INT NOT NULL,STAFF_NUMBER INT NOT NULL,OUTPATIENT_ID INT NOT NULL,APPOINTMENT_DATE DATE NOT NULL,APPOINTMENT_TIME VARCHAR(5) NOT NULL,EXAMINATION_ROOM VARCHAR(10) NOT NULL)

